"""Summarize this already-recorded actual quote observation; no HTTP, signals or new fills."""
from pathlib import Path
from datetime import datetime
from decimal import Decimal as D
import json
T=Path(__file__).resolve().parent;R=T.parents[3];load=lambda n:json.loads((T/n).read_text());r=load('report.json');m=load('market.json');before=load('state_before.json');after=load('state_after.json');dt=lambda s:datetime.fromisoformat(s.replace('Z','+00:00'))
elapsed=(dt(r['observed_at_utc'])-dt(r['cohort_started_at_utc'])).total_seconds();interval=(dt(r['observed_at_utc'])-dt(before['last_observed_at_utc'])).total_seconds();coverage=min(c['observation_coverage_fraction'] for c in r['configs'].values());totals={}
for k in ('1','2','3'):
 ss=[c['scenes'][k] for c in r['configs'].values()];nav=sum(D(z['NAV_usdt'])for z in ss);totals[k]={'NAV_usdt':str(nav),'net_PnL_usdt':str(nav-D(20000)),'net_return_pct':str(100*(nav/D(20000)-1)),'cost_usdt':str(sum(D(z['cost_usdt'])for z in ss)),'cost_parts_usdt':{p:str(sum(D(z['cost_parts'][p])for z in ss))for p in ('fee','half_spread','slippage','impact','tick_rounding')},'lifetime_virtual_fills':sum(z['executions']for z in ss),'lifetime_round_trips':sum(z['round_trips']for z in ss)}
ranked=[{'id':name,'indicators':c['label'],'raw_weights':c['raw_weights'],'NAV_usdt':c['scenes']['1']['NAV_usdt'],'net_PnL_usdt':c['scenes']['1']['net_PnL_usdt'],'net_return_pct':c['scenes']['1']['net_return_pct'],'sampled_drawdown_pct':c['scenes']['1']['observed_sample_max_drawdown_pct']}for name,c in sorted(r['configs'].items(),key=lambda z:(-z[1]['scenes']['1']['net_return_pct'],z[0]))]
summary={'observation_id':T.name,'observed_at_utc':r['observed_at_utc'],'actual_quote_observations':after['observations'],'elapsed_seconds':elapsed,'interval_since_prior_seconds':interval,'coverage_fraction':coverage,'coverage_scope':'Frozen two-hour target sampling count/time-gap proxy;not continuous quote or minute-path coverage.','new_gap':r['new_gap'],'retained_gaps':r['coverage_gaps'],'new_daily_decisions':len(r['decisions']),'new_virtual_fills':r['new_filled_virtual_orders'],'real_orders':r['real_orders'],'totals_by_cost':totals,'main_accounts_ranked_desc':ranked,'validation':{'walk_forward':f"180days/6x30day windows incomplete;{after['observations']} actual quote observations",'parameter_sensitivity':'Frozen parameters;historical sensitivity reference only,no tuning or strategy replacement','costs':'All30 cumulative1/2/3x account scenes marked;zero new fills/costs','risk':f"{after['observations']} actual quote snapshots only;no minute/tick risk proof,original gap retained"},'notification':'Routine;zero new trades,gap,milestone or frozen risk-threshold crossing.'}
assert not r['decisions'] and not r['trades'] and r['new_gap'] is None and all(c['scenes']['3']['observed_sample_max_drawdown_pct']<25 for c in r['configs'].values()) and elapsed<30*86400
# Write the final coverage classification once below.
lines=[f"# 第{after['observations']}次真实行情观察复核",'',f"实际观察UTC：{r['observed_at_utc']}；累计{elapsed/3600:.6f}小时；距上次{interval:.6f}秒。冻结起点{r['cohort_started_at_utc']}，目标结束{r['cohort_end_utc']}。",'', '本轮没有新的已闭合UTC日线。60个分仓现金、数量、desired、已处理日线、累计费用和交易历史保持；不重复信号或成交，0新虚拟成交、0真实订单。仅在实际收到本轮买卖报价后更新净值和采样回撤。','']
for a,q in m['quotes'].items():lines.append(f"{a}买一/卖一：{q['bid']} / {q['ask']}，接收UTC {q['observed_at_utc']}。")
lines+=['','bookTicker不提供交易所事件时间，保存本机接收时间；不把接收时效当成交所事件新鲜度或真实接单保证。持仓按实际观察中间价mark，累计收益已经扣除已发生虚拟交易成本，不提前扣未来平仓费。','', '| 独立成本场景 | 10组总净值USDT | 总盈亏USDT | 累计收益% | 累计虚拟成交 | 累计往返 | 累计成本USDT |','|---|---:|---:|---:|---:|---:|---:|']
for k,z in totals.items():lines.append(f"| {k}x | {z['NAV_usdt']} | {z['net_PnL_usdt']} | {float(z['net_return_pct']):.9f} | {z['lifetime_virtual_fills']} | {z['lifetime_round_trips']} | {z['cost_usdt']} |")
lines+=['',f"主账户累计手续费{totals['1']['cost_parts_usdt']['fee']}USDT，成交量相关冲击{totals['1']['cost_parts_usdt']['impact']}USDT；点差/滑点/取整明细在report.json，本轮没有新增成本。合计只用于10组独立账户展示，不是合并基金；2x/3x各自从同额资金持续核算。",'', '主账户收益倒序、指标参数、原始权重、持仓和1/2/3倍成本收益及采样回撤见result.md。P01/P03/P04/P06/P08/P09保持全现金；P02/P05/P07各持ETH0.19530000，P10持BTC0.01797000。','',f"冻结2小时计划覆盖指标{100*coverage:.6f}%，目前只有{after['observations']}次实际快照，不是连续分钟覆盖。无新缺口；累计{len(r['coverage_gaps'])}段原始缺口完整保留，缺失期间不倒填订单。回撤仅按保存的报价快照采样。",'', '尚无完整30天窗口，未满180天/6窗，不提前宣称策略验证通过。参数、初始分仓比例保持冻结；历史敏感性只作参考；观察登记rejected表示未成熟，账户继续，不淘汰、重启或重置本金。','', '10个新观察截止配置先reserve，再实际获取公开GET行情、核算并finish。实际输入/时序/哈希、精确状态/报告重放、余额守恒、同日幂等、登记及网页汇总进行必要检查。合成夹具只作工程检查，不作收益。26份源spec与固定提交逐字节匹配，16个组件的完整规则、冻结执行器、旧观察、研究结果及原SMA延迟shadow保持；无新研究回测或网页重新部署。','', f"复现：`.venv/bin/python research/paper10/run.py --reproduce {T.name}`；只读既有真实输入/报告/状态，不HTTP、不产生新成交。全部正负收益和零交易保存，远端确认后静默继续。"]
oldreport=json.loads((R/'research/paper10/observations'/before['last_observation_id']/'report.json').read_text());oldcoverage=min(c['observation_coverage_fraction']for c in oldreport['configs'].values())
coverage_changed=(oldcoverage>=.95)!=(coverage>=.95)
coverage_direction='up'if coverage_changed and coverage>=.95 else'down'if coverage_changed else None
summary['prior_coverage_fraction']=oldcoverage;summary['coverage_above95pct']=coverage>=.95;summary['coverage_risk_changed']=coverage_changed;summary['coverage_threshold_direction']=coverage_direction;summary['notification']=('Coverage95percent proxy threshold crossed '+coverage_direction+';all existing gaps retained,no180day qualification'if coverage_changed else'Routine:no new trade,gap,milestone or risk-threshold crossing')
(T/'summary.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
lines+=['','## 各主账户累计手续费与冲击','','|账户|累计手续费USDT|累计成交量冲击USDT|累计总成本USDT|','|---|---:|---:|---:|']
for name,c in sorted(r['configs'].items(),key=lambda z:(-z[1]['scenes']['1']['net_return_pct'],z[0])):
 z=c['scenes']['1'];lines.append(f"|{name}|{z['cost_parts']['fee']}|{z['cost_parts']['impact']}|{z['cost_usdt']}|")
lines+=['','## 冻结覆盖门槛复核','',f"前轮观察覆盖代理{100*oldcoverage:.6f}%，本轮{100*coverage:.6f}%；冻结95%门槛跨越方向={coverage_direction}。两段原始缺口及其时间完整保留，未倒填交易或改写过去快照。该指标按固定2小时目标计数与已记录缺口时长估算，回升来自持续记录和累计时长变化，不表示缺失行情已经补齐或获得连续分钟覆盖。",'', '覆盖单项满足不能替代180天/六个30天窗口、交易数及其他冻结门槛；当前仍未成熟，未宣称策略验证通过。初始本金、规则、数量、现金、费用、交易ID及旧账本保持。']
(T/'observation_review.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'observations':after['observations'],'actual_elapsed_hours':elapsed/3600,'main_NAV':totals['1']['NAV_usdt'],'main_PnL':totals['1']['net_PnL_usdt'],'coverage':coverage,'new_trades':0,'new_gap':False},ensure_ascii=False))
